### PR TITLE
Readme formatting. 

### PR DESCRIPTION
**Pull request by Servius**
- Large amount of formatting. Sorry for the amount of commits. Had to play around with it for a while to see what looked best. 
- Also fixed the custom check in the ammo.lua

### CODE REVIEW

**Comment by Servius** [comment]
Example of Readme

**Comment by strideynet** [comment]
For future reference:

http://stackoverflow.com/questions/6218184/compressing-many-commits-into-fewer-but-larger-commits

Keeps things neater and makes PRs more professional and people can't see internal commit names so you can swear in em.

**Comment by FPtje** [comment]
Please get rid of trailing whitespace.

**Comment by Servius** [comment]
Can't. Spaces are used for formatting on git. Trailing spaces tell the formatting thing that this line is not to get connected with the next line.

**Comment by Servius** [comment]
I can show you an example of what happens when I get rid of trailing spaces if you'd like.

**Comment by FPtje** [comment]
You do know that trailing spaces are the space characters at the *end* of a line, right?

**Comment by Servius** [comment]
yuppers. It's genuinely a formatting thing. Not an accident but an intentional double/ triple space depending on what I wanted that line to do in the next/current line.

**Comment by Servius** [comment]
I'll link the formatting resource that explains it.

**Comment by Servius** [comment]
[image](http://image.prntscr.com/image/1f0c387b591e42d793edc390b26e91a3.png)

**Comment by Servius** [comment]
I could have used two lines by using enter but that would end up with un-needed lines every single time I wanted to keep different statements separate from eachother.

**Comment by FPtje** [comment]
I'd rather you use empty lines than trailing whitespace.

**Comment by Servius** [comment]
image

**Comment by Servius** [comment]
compare
Not a huge issue.

**Comment by Servius** [comment]
I can switch it from spaces to lines if youd like.

**Comment by FPtje** [comment]
yes please

**Comment by Servius** [comment]
Done.

**Comment by FPtje** [comment]
Note that ammo.lua also has trailing whitespace. What editor do you use anyway? I believe Atom and Sublime remove trailing whitespace automatically.

**Comment by Servius** [comment]
I use sublime but for the readme its a github formatting technique recommended and supported by github. For the ammo.lua twaz only accidental spaces. Ill remove them but according to about 189 sources extra spaces, use of tabs, etc. have zero effect on the actual functionality of the code and wouldnt cause any bugs or issues. Ill fix it now.

**Comment by Servius** [comment]
Spaces removed.

**Comment by FPtje** [comment]
Thank you for your efforts

**Comment by Servius** [comment]
Anytime.

**Pull request merged**
