### PR TITLE
New/better examples/messages added for a handful of files. 

### PR DESCRIPTION
**Pull request by Servius**
- ammo.lua now has better examples to help the new-to-lua darkrp server owner. 
- helpful messages added to disabled_defaults.lua
- helpful messages added to vehicles.lua

### CODE REVIEW

**Comment by strideynet** [comment]
Changes are purely comment based and all grammar looks ok.
👍

**Comment by FPtje** [comment]
Thank you

**Comment by FPtje** [comment]
Please obey the usage of spaces instead of tabs.

**Comment by Servius** [comment]
What do you mean by spaces over tabs?

**Comment by Servius** [comment]
Just so I know what to do in the future.

**Comment by FPtje** [comment]
indentation. The whitespace at the start of a line.

**Comment by Servius** [comment]
I guess I should have been more clear, where did I do that?

**Comment by FPtje** [comment]
https://github.com/FPtje/darkrpmodification/pull/100/files#diff-31588d5ecc6c4bbd8e09b4897780bdeeR72

**Comment by Servius** [comment]
I tried keeping the same amount of spacing but I can see what you mean. Will try to do better with future commits. I'll probably be sticking to stuff like this. I usually do work on this whenever I encounter something I have to google or check the darkrp wiki to be able to accomplish. If you've got a section you'd like looked at feel free to let me know.

**Comment by FPtje** [comment]
Cheers!

**Pull request merged**
